language:
- objective-c
env:
  global:
  - BUILD_COMMIT=v1.1.1
  - REPO_DIR=astropy
  matrix:
  - VERSION=2.7.10 NUMPY_VERSION=1.6.2 NUMPY_TEST_VERSION=1.7.1
  # - VERSION=3.3.5 NUMPY_VERSION=1.7.1 NUMPY_TEST_VERSION=1.8.1
  - VERSION=3.4.3 NUMPY_VERSION=1.7.1 NUMPY_TEST_VERSION=1.8.1
  - VERSION=3.5.0 NUMPY_VERSION=1.9.3 NUMPY_TEST_VERSION=1.9.3 # mpl built against 1.9
install:
  - source terryfy/travis_tools.sh
  - get_python_environment macpython $VERSION venv
  # Update wheel for Python 3.5
  - pip install -U wheel
  - pip install delocate
  # Allow nipy wheelhouse for Python 3.5 wheel
  - pip install -f $NIPY_WHEELHOUSE numpy==$NUMPY_VERSION
  # Use clang to avoid warnings on Python 3.5
  - export CC=clang
  - export CXX=clang++
  - pip install pyyaml psutil Cython jinja2 pytest scipy h5py matplotlib beautifulsoup4
  - if [ -n "$BUILD_COMMIT" ]; then
      checkout_commit $REPO_DIR $BUILD_COMMIT;
    fi
  - cd $REPO_DIR
  - python setup.py bdist_wheel
  - delocate-listdeps dist/*.whl # lists library dependencies
  - delocate-wheel dist/*.whl # copies library dependencies into wheel
  - delocate-addplat --rm-orig -x 10_9 -x 10_10 dist/*.whl
  - pip install dist/*.whl
  - cd ..
script:
  # install dependencies for tests e.g - pip install nose
  - mkdir tmp_for_test
  - cd tmp_for_test
  # Install needed numpy version for tests
  - pip install numpy==$NUMPY_TEST_VERSION
  # Run the tests
  - python -c 'import sys; import astropy; sys.exit(astropy.test())'
  - cd ..
before_deploy:
  - cd $REPO_DIR/dist
deploy:
  provider: cloudfiles
  edge: true
  username: travis-worker
  api_key:
      secure: "eRvhZ4GkrB6sUpH4tNHvdgN91Jrhl+F+7J4BXuH3Kql9kCrXlLvH+TtoYsDX1x6zAFJy1eVePtNbwMdzFcWP9koQXPHD2+o7U6AFomCN8KjJxd7ha8K7HDWbvn+R+bn1/tr0Fz04pyqlLyzM0pe+QO4JvcHQ+8TsDKuIDi9cYUE="
  region: ORD
  container: wheels
  skip_cleanup: true
