env:
  global:
      - REPO_DIR=astropy
      - BUILD_COMMIT=v1.2rc1
      - UNICODE_WIDTHS="16 32"
      - NP_BUILD_DEP="numpy==1.7.1"
      - NP_TEST_DEP="numpy==1.7.1"
      - GEN_DEPS="pyyaml psutil jinja2 scipy h5py matplotlib beautifulsoup4"

language: python
sudo: required
dist: trusty
services: docker

matrix:
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.4
    - os: linux
      python: 3.5
      env:
        - NP_BUILD_DEP=numpy==1.9.3
        - NP_TEST_DEP=numpy==1.9.3
    - os: osx
      language: objective-c
      env: TRAVIS_PYTHON_VERSION=2.7
    - os: osx
      language: objective-c
      env: TRAVIS_PYTHON_VERSION=3.4
    - os: osx
      language: objective-c
      env:
        - TRAVIS_PYTHON_VERSION=3.5
        - NP_BUILD_DEP=numpy==1.9.3
        - NP_TEST_DEP=numpy==1.9.3

before_install:
    - BUILD_DEPENDS="$NP_BUILD_DEP Cython $GEN_DEPS"
    - TEST_DEPENDS="$NP_TEST_DEP pytest $GEN_DEPS"
    - source multibuild/travis_steps.sh
    - before_install

install:
    - git clone https://github.com/facebook/tornado
    - build_wheels
    - install_wheel

install:
    - build_wheels
    - install_wheel

script:
    - mkdir tmp_for_test
    - cd tmp_for_test
    # Run the tests
    - python -c 'import sys; import astropy; sys.exit(astropy.test())'
    - cd ..

before_deploy:
    - cd wheelhouse

deploy:
  provider: cloudfiles
  edge: true
  username: travis-worker
  api_key:
      secure: "eRvhZ4GkrB6sUpH4tNHvdgN91Jrhl+F+7J4BXuH3Kql9kCrXlLvH+TtoYsDX1x6zAFJy1eVePtNbwMdzFcWP9koQXPHD2+o7U6AFomCN8KjJxd7ha8K7HDWbvn+R+bn1/tr0Fz04pyqlLyzM0pe+QO4JvcHQ+8TsDKuIDi9cYUE="
  region: ORD
  container: wheels
  skip_cleanup: true
